# Generated by Django 4.2 on 2023-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Helmets', 'Helmets'), ('Gloves', 'Gloves'), ('Bags', 'Bags'), ('Jackets', 'Jackets')], default='Jackets', max_length=20),
        ),
    ]
